### ISSUE TITLE
 undefined method `each_pair' for nil:NilClass with gitlab rails application

### ISSUE THREAD

**Issue by harshanails** [danmayer/coverband#468]
**Describe the bug**
```
rake coverband:coverage --trace
** Invoke coverband:coverage (first_time)
** Execute coverband:coverage
rake aborted!
NoMethodError: undefined method `each_pair' for nil:NilClass
/Users/harshamuralidhar/.asdf/installs/ruby/3.0.5/lib/ruby/gems/3.0.0/gems/coverband-5.2.5/lib/coverband/reporters/console_report.rb:11:in `report'
/Users/harshamuralidhar/.asdf/installs/ruby/3.0.5/lib/ruby/gems/3.0.0/gems/coverband-5.2.5/lib/coverband/utils/tasks.rb:17:in `block (2 levels) in <top (required)>'
/Users/harshamuralidhar/.asdf/installs/ruby/3.0.5/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/Users/harshamuralidhar/.asdf/installs/ruby/3.0.5/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/Users/harshamuralidhar/.asdf/installs/ruby/3.0.5/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/Users/harshamuralidhar/.asdf/installs/ruby/3.0.5/lib/ruby/gems/3.0.0/gems/sentry-ruby-core-5.1.1/lib/sentry/rake.rb:24:in `execute'
/Users/harshamuralidhar/.asdf/installs/ruby/3.0.5/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/Users/harshamuralidhar/.asdf/installs/ruby/3.0.5/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/Users/harshamuralidhar/.asdf/installs/ruby/3.0.5/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/Users/harshamuralidhar/.asdf/installs/ruby/3.0.5/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/Users/harshamuralidhar/.asdf/installs/ruby/3.0.5/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
/Users/harshamuralidhar/.asdf/installs/ruby/3.0.5/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/harshamuralidhar/.asdf/installs/ruby/3.0.5/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/Users/harshamuralidhar/.asdf/installs/ruby/3.0.5/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/Users/harshamuralidhar/.asdf/installs/ruby/3.0.5/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/Users/harshamuralidhar/.asdf/installs/ruby/3.0.5/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/Users/harshamuralidhar/.asdf/installs/ruby/3.0.5/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:83:in `block in run'
/Users/harshamuralidhar/.asdf/installs/ruby/3.0.5/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/harshamuralidhar/.asdf/installs/ruby/3.0.5/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
/Users/harshamuralidhar/.asdf/installs/ruby/3.0.5/lib/ruby/gems/3.0.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/Users/harshamuralidhar/.asdf/installs/ruby/3.0.5/bin/rake:25:in `load'
/Users/harshamuralidhar/.asdf/installs/ruby/3.0.5/bin/rake:25:in `<main>'
```
**To Reproduce**
1. Make sure `rake -T coverband --trace` command is working and make sure `COVERBAND_REDIS_URL` is set.
2. Make sure route `/coverage` is defined in routes.rb.
3. Run `rake coverband:coverage`

**Expected behavior**
Coverage should be reported in the path `/coverage`.
**Screenshots**

**Desktop (please complete the following information):**
 -  MacOS Ventura 13.1

**Smartphone (please complete the following information):**

**Additional context**
I am using an external redis server, not the one used by gitlab app.

**Comment by harshanails** [comment]
Oh, when i opened the application and performed some actions on the app, the command `rake coverband:coverage` worked.

**Comment by harshanails** [comment]
Though I am seeing `undefined method `instance_observe_duration' for nil:NilClass` in `/coverage` path.

**Comment by harshanails** [comment]
> Oh, when i opened the application and performed some actions on the app, the command `rake coverband:coverage` worked.

I can confirm that when no test/action is performed on the rails application, it throws the `undefined method each_pair for nil:NilClass`  error. On running, `rake coverband:clear` I was able to reproduce the behaviour.

**Comment by harshanails** [comment]
Although I am still having trouble mounting the coverage path in the rails app, I will close this issue.

**Comment by harshanails** [comment]
> I can confirm that when no test/action is performed on the rails application before running rake coverband:coverage, it throws the `undefined method each_pair for nil:NilClass` error. On running, `rake coverband:clear` I was able to reproduce the behaviour.

Actually I am back to square one. Even after performing actions on the rails app it throws this error :(

**Comment by danmayer** [comment]
Sorry, I haven't looked at this, I need some time to pull down gitlab rails and to better understand what exactly is going on

**Comment by harshanails** [comment]
I tried this again, but just mounting the `coverage` route in config/routes.rb of the Gitlab rails app and adding `coverband` to the Gemfile.
Seeing the following error in Gitlab rails log:
```
Class> undefined method `instance_observe_duration' for nil:NilClass
2024-04-18_03:09:41.90959 rails-web             : E, [2024-04-18T13:09:41.909495 #57889] ERROR -- : Coverband: view_tracker failed to store, error NoMethodError
2024-04-18_03:09:47.44703 rails-web             : E, [2024-04-18T13:09:47.446805 #57887] ERROR -- : coverage failed to store
2024-04-18_03:09:47.44714 rails-web             : E, [2024-04-18T13:09:47.447015 #57887] ERROR -- : Coverband Error: #<NoMethodError: undefined method `instance_observe_duration' for nil:NilClass> undefined method `instance_observe_duration' for nil:NilClass
2024-04-18_03:09:47.44728 rails-web             : E, [2024-04-18T13:09:47.447180 #57887] ERROR -- : Coverband: view_tracker failed to store, error NoMethodError
```

**Comment by harshanails** [comment]
It could be because the local setup of the Gitlab application also uses a redis server.

**Comment by harshanails** [comment]
When I shutdown the `redis-server` on `localhost:6379`, the error is:
```
2024-04-18_04:40:04.69467 rails-web             : E, [2024-04-18T14:40:04.694487 #89350] ERROR -- : coverage failed to store
2024-04-18_04:40:04.69480 rails-web             : E, [2024-04-18T14:40:04.694659 #89350] ERROR -- : Coverband Error: #<Redis::CannotConnectError: Connection refused - connect(2) for [::1]:6379 (redis://localhost:6379)> Connection refused - connect(2) for [::1]:6379 (redis://localhost:6379)
2024-04-18_04:40:04.69638 rails-web             : E, [2024-04-18T14:40:04.696243 #89350] ERROR -- : Coverband: Coverband::Collectors::ViewTracker failed to store, error Redis::CannotConnectError info Connection refused - connect(2) for [::1]:6379 (redis://localhost:6379)
2024-04-18_04:40:27.19944 rails-web             : Since there is no EDITOR or BETTER_ERRORS_EDITOR environment variable, using Textmate by default.
2024-04-18_04:40:27.21010 rails-web             : E, [2024-04-18T14:40:27.209914 #89349] ERROR -- : coverage failed to store
2024-04-18_04:40:27.21110 rails-web             : E, [2024-04-18T14:40:27.210952 #89349] ERROR -- : Coverband Error: #<Redis::CannotConnectError: Connection refused - connect(2) for [::1]:6379 (redis://localhost:6379)> Connection refused - connect(2) for [::1]:6379 (redis://localhost:6379)
2024-04-18_04:40:27.21733 rails-web             : E, [2024-04-18T14:40:27.217188 #89349] ERROR -- : Coverband: Coverband::Collectors::ViewTracker failed to store, error Redis::CannotConnectError info Connection refused - connect(2) for [::1]:6379 (redis://localhost:6379)
```

**Comment by danmayer** [comment]
so is this just pulling down gitlab and then running it on the main branch and then trying to add coverband? If so I can try to reproduce that... I have never used git lab so I don't know much about it.

**Comment by danmayer** [comment]
is this an open source code repository I can try to get a copy of to run and fix it or is this a closed source repo...

**Comment by danmayer** [comment]
If it is this repo I can give it a shot https://github.com/gitlabhq/gitlabhq.git

**Comment by danmayer** [comment]
oof getting gitlab running is quite the task it is a huge install... but I will give it a go

**Comment by harshanails** [comment]
Update: I was able to get it working with the Gitlab rails app with this config:
https://gitlab.com/gitlab-org/gitlab/-/merge_requests/149950/diffs?pin=e2b741f5feac38042b9bcc53faa2abe9f6dafaae#e2b741f5feac38042b9bcc53faa2abe9f6dafaae_0_6

**Comment by danmayer** [comment]
nice @harshanails that is amazing. Let me know how it works for you all or  if you need help tweaking any configuration values.

I generally recommend setting a longer  `background_reporting_sleep_seconds` but if this is just on a test server vs a larger cluster it should be fine... If you are running on a bunch of machines tweaking that and some other options will help avoid overloading your redis.

Thanks for spending time to figure it all out. I am looking forward to hearing if it works well for you all.

**Comment by danmayer** [comment]
OK, since this issue is fixed I am going to close it but feel free to keep adding comments or updates... or open a new issue if you have any problems or questions.

**Comment by harshanails** [comment]
> OK, since this issue is fixed I am going to close it but feel free to keep adding comments or updates... or open a new issue if you have any problems or questions.

Thanks @danmayer!

It is working well for our use case, but I have a question regarding `config.background_reporting_sleep_seconds` configuration. Is this config for "how often coverband persists coverage data to redis cache?"

**Comment by danmayer** [comment]
yes `config.background_reporting_sleep_seconds` is how long it waits between sending reports to redis. So having that longer will put less load on your redis but will mean your coverage is less up to date. If you are running many servers increasing that along with the reporting wiggle will help avoid to many reports hitting redis at the same time. The coverage is aggregated in memory between each report.

Note that it reports per process so how many workers are buidling reports and sending to redis depends on your webserver and configurations for example using Puma with threads will have a shared reporter per puma process.

**Comment by harshanails** [comment]
> yes `config.background_reporting_sleep_seconds` is how long it waits between sending reports to redis. So having that longer will put less load on your redis but will mean your coverage is less up to date. If you are running many servers increasing that along with the reporting wiggle will help avoid to many reports hitting redis at the same time. The coverage is aggregated in memory between each report.
> 
> Note that it reports per process so how many workers are buidling reports and sending to redis depends on your webserver and configurations for example using Puma with threads will have a shared reporter per puma process.

Thank you, that was a helpful response. 
Another question I had was - I have require 'false' in the Gemfile for coverband because for our use case, we don't want it to be part of the production application.

So question is basically - does the background reporting start as soon as require 'coverband' is called in the code? And will restarting the rails application stop the background reporting? Is there a way to stop the background reporting by calling a function perhaps?

**Comment by Lx09** [comment]
> config.store = Coverband::Adapters::RedisStore.new(::Redis.new(url: 'redis://localhost:6379',
>     custom: { instrumentation_class: 'SharedState' }))

I am still encountering the error message "Coverband: Coverband::Collectors::ViewTracker failed to store, error NoMethodError info undefined method `instance_observe_duration' for nil:NilClas" error messages when trying to use coverband with an older version of gitlab (v13.10.3). I am deploying gitlab in docker container. Below are my docker-compose, dockerfile and configuration files.

dockerfile
```dockerfile
FROM gitlab/gitlab-ce:13.10.3-ce.0

COPY ./coverband.rb /opt/gitlab/embedded/service/gitlab-rails/config/initializers/zz_coverband.rb

RUN echo "gem 'coverband', '6.1.2', require: false" >> /opt/gitlab/embedded/service/gitlab-rails/Gemfile && cd /opt/gitlab/embedded/service/gitlab-rails && bundle install
```

docker-compose.yml
```docker-compose
services:
  redis:
    container_name: test
    restart: always
    image: redis:4.0.2 # I've already tried 5.0.9 and 7.x.x, all not work
  gitlab:
    depends_on: 
      - redis
    build: .
    ports:
      - "10080:80"
```

coverband.rb
```ruby
require 'coverband'
puts "required coverband"
Coverband.configure do |config|
    config.store = Coverband::Adapters::RedisStore.new(::Redis.new(url: 'redis://test:6379',
    custom: { instrumentation_class: 'SharedState' }))  
    config.background_reporting_sleep_seconds = 1
    config.reporting_wiggle = nil # Since this is not run in production disable wiggle and report every second.
    config.ignore += %w[spec/.* lib/tasks/.*
        config/application.rb config/boot.rb config/initializers/.* db/post_migrate/.*
        config/puma.rb bin/.* config/environments/.* db/migrate/.*]

    config.verbose = true
    config.csp_policy = true
    config.logger = Gitlab::AppLogger
end
```

When the gitlab is running, I notice that the message "required coverband" I printed appears twice, which indicates that coverband is being loaded twice. I don't think that this is as it should be. Additionally, I receive the following error messages:

```bash
gitlab-1  | ==> /var/log/gitlab/gitlab-rails/application.log <==
gitlab-1  | 2025-02-04T17:27:37.769Z: coverage failed to store
gitlab-1  | 
gitlab-1  | ==> /var/log/gitlab/gitlab-rails/application_json.log <==
gitlab-1  | {"severity":"ERROR","time":"2025-02-04T17:27:37.769Z","correlation_id":null,"message":"coverage failed to store"}
gitlab-1  | 
gitlab-1  | ==> /var/log/gitlab/gitlab-rails/application.log <==
gitlab-1  | 2025-02-04T17:27:37.772Z: Coverband Error: #<NoMethodError: undefined method `instance_observe_duration' for nil:NilClass> undefined method `instance_observe_duration' for nil:NilClass
gitlab-1  | 
gitlab-1  | ==> /var/log/gitlab/gitlab-rails/application_json.log <==
gitlab-1  | {"severity":"ERROR","time":"2025-02-04T17:27:37.772Z","correlation_id":null,"message":"Coverband Error: #\u003cNoMethodError: undefined method `instance_observe_duration' for nil:NilClass\u003e undefined method `instance_observe_duration' for nil:NilClass"}
gitlab-1  | 
gitlab-1  | ==> /var/log/gitlab/gitlab-rails/application.log <==
gitlab-1  | 2025-02-04T17:27:37.772Z: /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/instrumentation/redis_interceptor.rb:23:in `ensure in call'
gitlab-1  | 
gitlab-1  | ==> /var/log/gitlab/gitlab-rails/application_json.log <==
gitlab-1  | {"severity":"ERROR","time":"2025-02-04T17:27:37.773Z","correlation_id":null,"message":"/opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/instrumentation/redis_interceptor.rb:23:in `ensure in call'"}
gitlab-1  | {"severity":"ERROR","time":"2025-02-04T17:27:37.773Z","correlation_id":null,"message":"/opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/instrumentation/redis_interceptor.rb:30:in `call'"}
gitlab-1  | {"severity":"ERROR","time":"2025-02-04T17:27:37.773Z","correlation_id":null,"message":"/opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/redis-4.1.3/lib/redis.rb:914:in `block in get'"}
gitlab-1  | {"severity":"ERROR","time":"2025-02-04T17:27:37.773Z","correlation_id":null,"message":"/opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/redis-4.1.3/lib/redis.rb:52:in `block in synchronize'"}
gitlab-1  | {"severity":"ERROR","time":"2025-02-04T17:27:37.773Z","correlation_id":null,"message":"/opt/gitlab/embedded/lib/ruby/2.7.0/monitor.rb:202:in `synchronize'"}
gitlab-1  | 
gitlab-1  | ==> /var/log/gitlab/gitlab-rails/application.log <==
gitlab-1  | 2025-02-04T17:27:37.773Z: /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/instrumentation/redis_interceptor.rb:30:in `call'
gitlab-1  | 2025-02-04T17:27:37.773Z: /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/redis-4.1.3/lib/redis.rb:914:in `block in get'
gitlab-1  | 2025-02-04T17:27:37.773Z: /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/redis-4.1.3/lib/redis.rb:52:in `block in synchronize'
gitlab-1  | 2025-02-04T17:27:37.773Z: /opt/gitlab/embedded/lib/ruby/2.7.0/monitor.rb:202:in `synchronize'
gitlab-1  | 2025-02-04T17:27:37.774Z: /opt/gitlab/embedded/lib/ruby/2.7.0/monitor.rb:202:in `mon_synchronize'
gitlab-1  | 2025-02-04T17:27:37.774Z: /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/redis-4.1.3/lib/redis.rb:52:in `synchronize'
gitlab-1  | 2025-02-04T17:27:37.774Z: /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/redis-4.1.3/lib/redis.rb:913:in `get'
gitlab-1  | 2025-02-04T17:27:37.774Z: /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/coverband-6.1.2/lib/coverband/adapters/redis_store.rb:77:in `coverage'
gitlab-1  | 2025-02-04T17:27:37.774Z: /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/coverband-6.1.2/lib/coverband/adapters/redis_store.rb:89:in `save_report'
gitlab-1  | 2025-02-04T17:27:37.775Z: /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/coverband-6.1.2/lib/coverband/collectors/coverage.rb:71:in `block in report_coverage'
gitlab-1  | 2025-02-04T17:27:37.775Z: /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/coverband-6.1.2/lib/coverband/collectors/coverage.rb:58:in `synchronize'
gitlab-1  | 2025-02-04T17:27:37.775Z: /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/coverband-6.1.2/lib/coverband/collectors/coverage.rb:58:in `report_coverage'
gitlab-1  | 2025-02-04T17:27:37.775Z: /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/coverband-6.1.2/lib/coverband.rb:69:in `report_coverage'
gitlab-1  | 2025-02-04T17:27:37.775Z: /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/coverband-6.1.2/lib/coverband/integrations/background.rb:40:in `block (3 levels) in start'
gitlab-1  | 2025-02-04T17:27:37.775Z: /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/coverband-6.1.2/lib/coverband/integrations/background.rb:33:in `loop'
gitlab-1  | 2025-02-04T17:27:37.776Z: /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/coverband-6.1.2/lib/coverband/integrations/background.rb:33:in `block (2 levels) in start'
gitlab-1  | 
gitlab-1  | ==> /var/log/gitlab/gitlab-rails/application_json.log <==
gitlab-1  | {"severity":"ERROR","time":"2025-02-04T17:27:37.774Z","correlation_id":null,"message":"/opt/gitlab/embedded/lib/ruby/2.7.0/monitor.rb:202:in `mon_synchronize'"}
gitlab-1  | {"severity":"ERROR","time":"2025-02-04T17:27:37.774Z","correlation_id":null,"message":"/opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/redis-4.1.3/lib/redis.rb:52:in `synchronize'"}
gitlab-1  | {"severity":"ERROR","time":"2025-02-04T17:27:37.774Z","correlation_id":null,"message":"/opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/redis-4.1.3/lib/redis.rb:913:in `get'"}
gitlab-1  | {"severity":"ERROR","time":"2025-02-04T17:27:37.774Z","correlation_id":null,"message":"/opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/coverband-6.1.2/lib/coverband/adapters/redis_store.rb:77:in `coverage'"}
gitlab-1  | {"severity":"ERROR","time":"2025-02-04T17:27:37.774Z","correlation_id":null,"message":"/opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/coverband-6.1.2/lib/coverband/adapters/redis_store.rb:89:in `save_report'"}
gitlab-1  | {"severity":"ERROR","time":"2025-02-04T17:27:37.775Z","correlation_id":null,"message":"/opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/coverband-6.1.2/lib/coverband/collectors/coverage.rb:71:in `block in report_coverage'"}
gitlab-1  | {"severity":"ERROR","time":"2025-02-04T17:27:37.775Z","correlation_id":null,"message":"/opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/coverband-6.1.2/lib/coverband/collectors/coverage.rb:58:in `synchronize'"}
gitlab-1  | {"severity":"ERROR","time":"2025-02-04T17:27:37.775Z","correlation_id":null,"message":"/opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/coverband-6.1.2/lib/coverband/collectors/coverage.rb:58:in `report_coverage'"}
gitlab-1  | {"severity":"ERROR","time":"2025-02-04T17:27:37.775Z","correlation_id":null,"message":"/opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/coverband-6.1.2/lib/coverband.rb:69:in `report_coverage'"}
gitlab-1  | {"severity":"ERROR","time":"2025-02-04T17:27:37.775Z","correlation_id":null,"message":"/opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/coverband-6.1.2/lib/coverband/integrations/background.rb:40:in `block (3 levels) in start'"}
gitlab-1  | {"severity":"ERROR","time":"2025-02-04T17:27:37.776Z","correlation_id":null,"message":"/opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/coverband-6.1.2/lib/coverband/integrations/background.rb:33:in `loop'"}
gitlab-1  | {"severity":"ERROR","time":"2025-02-04T17:27:37.776Z","correlation_id":null,"message":"/opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/coverband-6.1.2/lib/coverband/integrations/background.rb:33:in `block (2 levels) in start'"}
```

Could you please help me wiith this problem?
